### PR TITLE
Bump to 0.17.0 and Add graphql support

### LINKED ISSUE #65: Monaco-editor-webpack-plugin, language configuration lacks graphql
Monaco-editor-webpack-plugin, language configuration lacks graphql, file is located in monaco-editor-webpack-plugin/languages.js

### PR DESCRIPTION
**Pull request by rkrasiuk**
fixes #65

### CODE REVIEW

**Comment by AmanDhembla** [comment]
Hey @judeallred when will this change get merged?

**Comment by judeallred** [comment]
Sure wish I could tell you, @AmanDhembla , but I'm just a random guy from the internet who hit the 'approve' button in the hopes that it'd help this PR move along.  :-)

**Comment by judeallred** [comment]
Little help, @alexandrudima  ? :-)   Or if not the graphql bit, at least the version bump to 0.17?

**Comment by KevinTCoughlin** [comment]
@alexandrudima, it would be nice to bump the peer dependency of `monaco-editor` to `^0.17.0`.

We have some repositories using the strict peer dependency feature of PNPM which require workaround to use the latest editor.

**Comment by alexdima** [comment]
Thank you! :heart:

**Pull request merged**
